### ISSUE TITLE
More wallpapers with the same style?

### ISSUE THREAD

**Issue by lokesh-krishna** [enindu/dotfiles#1]
Wonderful work here. Is the wallpaper from the Gruvbox rice (and the rest like it in the wallpapers directory) an original creation or is there more of it that I can find anywhere online? Really loving that style and would love to know if I can get some like that for the apps and distro I've got.  

If it is OC then I just want to congratulate you for creating something this splendid!

**Comment by enindu** [comment]
Thanks! Most of wallpapers are **semi** OCs except those solarized ones. To be honest, I'm not a graphic designer at all. Finding artworks on Google, changing colors, tuning them up and like that. I already linked the Git repo of solarized wallpapers but it seems not working now.
